// ── AUTO-GENERATED per-funnel param schema (from template sources) ──
// Used by the Change Agent to know exactly what it may edit per funnel.
export type ParamDef = { name: string; default: string }
export const FUNNEL_PARAMS: Record<string, ParamDef[]> = {
  "event-landing": [{ name: "eventName", default: "The Funnel Growth Summit 2026" }, { name: "date", default: "October 15\u201317, 2026" }, { name: "location", default: "Live Virtual + Albuquerque, NM" }, { name: "promise", default: "Walk Away Knowing Exactly How to Fill Your Next Event and Close $10K+ Sponsors" }, { name: "audience", default: "coaches, consultants, and agency owners running (or planning) their first paid e" }, { name: "host", default: "Jordan McKnight" }, { name: "hostCred", default: "Builder of McKnight GrowthOS \u2014 monetization systems for events, tax firms, and c" }, { name: "seats", default: "53" }, { name: "registered", default: "1,247" }, { name: "gaPrice", default: "$97" }, { name: "vipPrice", default: "$297" }, { name: "elitePrice", default: "$997" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "sponsor-deck": [{ name: "eventName", default: "The Funnel Growth Summit 2026" }, { name: "date", default: "October 15\u201317, 2026" }, { name: "location", default: "Live Virtual + Albuquerque, NM" }, { name: "attendees", default: "1,300+" }, { name: "audience", default: "coaches, consultants, and agency owners \u2014 68% doing $10K\u2013$100K/mo in revenue" }, { name: "contact", default: "sponsors@rjbusinesssolutions.org" }, { name: "titlePrice", default: "$15,000" }, { name: "goldPrice", default: "$7,500" }, { name: "silverPrice", default: "$2,500" }, { name: "titleSpots", default: "1" }, { name: "goldSpots", default: "2" }],
  "tax-lead": [{ name: "firmName", default: "Jefferson Tax Resolution Group" }, { name: "credential", default: "Enrolled Agents (EA) & CPAs" }, { name: "state", default: "New Mexico" }, { name: "years", default: "12" }, { name: "casesHandled", default: "2,400+" }, { name: "phone", default: "(505) 555-0134" }],
  "credit-service": [{ name: "companyName", default: "TrueNorth Credit Solutions" }, { name: "state", default: "New Mexico" }, { name: "clientsHelped", default: "3,100+" }, { name: "essentialPrice", default: "$99" }, { name: "essentialSetup", default: "$150" }, { name: "acceleratedPrice", default: "$179" }, { name: "acceleratedSetup", default: "$249" }, { name: "flatPrice", default: "$1,095" }],
  "credit-saas": [{ name: "productName", default: "DisputeForge" }, { name: "tagline", default: "The Credit Repair Software Built with Compliance Controls \u2014 and Built to Grow" }, { name: "starterPrice", default: "$97" }, { name: "growthPrice", default: "$197" }, { name: "scalePrice", default: "$397" }],
  "real-estate": [{ name: "agentName", default: "Jordan McKnight" }, { name: "brokerage", default: "Summit Realty Group" }, { name: "city", default: "Albuquerque" }, { name: "homesSold", default: "340+" }, { name: "avgDays", default: "11" }, { name: "avgOver", default: "4.2%" }, { name: "phone", default: "(505) 555-0177" }],
  "fitness": [{ name: "programName", default: "The 90-Day Reset" }, { name: "coachName", default: "Coach Rick" }, { name: "promise", default: "Drop the Weight, Keep the Muscle, and Never \"Start Over\" Again" }, { name: "audience", default: "busy professionals over 30 who are done with crash diets" }, { name: "clientCount", default: "1,200+" }, { name: "price", default: "$197/mo" }, { name: "vipPrice", default: "$497/mo" }, { name: "spots", default: "15" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "coaching": [{ name: "programName", default: "The Scale Accelerator" }, { name: "coachName", default: "Jordan McKnight" }, { name: "promise", default: "Install the Systems That Take You From Operator to Owner in 12 Months" }, { name: "audience", default: "founders and consultants doing $10K\u2013$50K/month who are the bottleneck in their o" }, { name: "revenue", default: "$40M+" }, { name: "clientCount", default: "215" }, { name: "investment", default: "$12,000" }],
  "ecommerce": [{ name: "productName", default: "HydraCore Pro" }, { name: "brandName", default: "HydraCore" }, { name: "promise", default: "The Insulated Bottle That Keeps Ice Frozen for 48 Hours \u2014 Guaranteed" }, { name: "category", default: "premium insulated water bottle" }, { name: "price", default: "$49" }, { name: "compareAt", default: "$79" }, { name: "bundlePrice", default: "$89" }, { name: "reviews", default: "12,400+" }, { name: "rating", default: "4.8" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "saas-trial": [{ name: "productName", default: "PipelinePilot" }, { name: "tagline", default: "Stop Losing Deals in Spreadsheet Hell \u2014 Close 27% More With a CRM Your Team Will" }, { name: "audience", default: "sales teams of 2\u201350 who\\'ve outgrown spreadsheets but hate bloated CRMs" }, { name: "userCount", default: "8,400+" }, { name: "starterPrice", default: "$29" }, { name: "proPrice", default: "$79" }, { name: "teamPrice", default: "$149" }, { name: "trialDays", default: "14" }],
  "law-firm": [{ name: "firmName", default: "Jefferson & Associates Injury Law" }, { name: "practiceArea", default: "personal injury" }, { name: "city", default: "Albuquerque" }, { name: "recovered", default: "$120M+" }, { name: "casesWon", default: "2,800+" }, { name: "years", default: "22" }, { name: "phone", default: "(505) 555-0199" }],
  "home-services": [{ name: "companyName", default: "Summit Roofing & Exteriors" }, { name: "service", default: "roof replacement" }, { name: "city", default: "Albuquerque" }, { name: "jobsDone", default: "4,600+" }, { name: "years", default: "18" }, { name: "warranty", default: "25-year" }, { name: "discount", default: "$750 OFF" }, { name: "phone", default: "(505) 555-0142" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "med-spa": [{ name: "spaName", default: "Luxe Aesthetics Med Spa" }, { name: "treatment", default: "laser skin rejuvenation" }, { name: "city", default: "Albuquerque" }, { name: "clientCount", default: "9,200+" }, { name: "offerPrice", default: "$99" }, { name: "offerValue", default: "$350" }, { name: "provider", default: "Dr. Elena Vasquez, MD" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "insurance": [{ name: "agencyName", default: "Jefferson Financial Group" }, { name: "productLine", default: "life insurance" }, { name: "state", default: "New Mexico" }, { name: "familiesServed", default: "5,300+" }, { name: "carrierCount", default: "40+" }, { name: "startingPrice", default: "$23/mo" }, { name: "phone", default: "(505) 555-0166" }],
  "agency": [{ name: "agencyName", default: "McKnight Growth Partners" }, { name: "niche", default: "home service businesses" }, { name: "service", default: "done-for-you lead generation" }, { name: "clientCount", default: "140+" }, { name: "leadsGenerated", default: "312,000+" }, { name: "avgRoas", default: "5.4x" }, { name: "retainer", default: "$2,500/mo" }],
  "restaurant": [{ name: "bizName", default: "Casa Bella Trattoria" }, { name: "cuisine", default: "wood-fired Italian" }, { name: "city", default: "Albuquerque" }, { name: "offer", default: "Free appetizer + dessert for two" }, { name: "offerValue", default: "$34" }, { name: "rating", default: "4.8" }, { name: "reviewCount", default: "1,240+" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "dental": [{ name: "practice", default: "Summit Smiles Dental" }, { name: "dentist", default: "Dr. Maria Torres, DDS" }, { name: "city", default: "Albuquerque" }, { name: "offer", default: "New Patient Exam + X-Rays + Cleaning" }, { name: "offerPrice", default: "$99" }, { name: "offerValue", default: "$385" }, { name: "patientCount", default: "12,000+" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "auto-services": [{ name: "shopName", default: "Precision Auto Care" }, { name: "city", default: "Albuquerque" }, { name: "service", default: "full-service auto repair" }, { name: "offer", default: "$29 Full-Vehicle Inspection + Oil Change" }, { name: "offerValue", default: "$129" }, { name: "warranty", default: "24-month / 24,000-mile" }, { name: "rating", default: "4.9" }, { name: "reviewCount", default: "870+" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "salon": [{ name: "salonName", default: "Luxe Studio Salon" }, { name: "city", default: "Albuquerque" }, { name: "specialty", default: "balayage & precision color" }, { name: "offer", default: "30% Off Your First Color + Free Deep-Conditioning Treatment" }, { name: "offerValue", default: "$85" }, { name: "stylistCount", default: "9" }, { name: "rating", default: "4.9" }, { name: "reviewCount", default: "640+" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "mortgage": [{ name: "loName", default: "Marcus Reed" }, { name: "company", default: "Summit Home Lending" }, { name: "nmls", default: "NMLS #123456" }, { name: "city", default: "Albuquerque" }, { name: "rate", default: "5.99%" }, { name: "program", default: "first-time buyer" }, { name: "closedCount", default: "1,400+" }, { name: "avgDays", default: "18" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "chiropractic": [{ name: "clinic", default: "Align Spine & Wellness" }, { name: "doctor", default: "Dr. Maya Torres, DC" }, { name: "city", default: "Albuquerque" }, { name: "offer", default: "Exam + Consultation + First Adjustment" }, { name: "offerPrice", default: "$49" }, { name: "offerValue", default: "$265" }, { name: "patientCount", default: "8,500+" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "pet-care": [{ name: "bizName", default: "Happy Tails Veterinary & Grooming" }, { name: "city", default: "Albuquerque" }, { name: "service", default: "veterinary care & grooming" }, { name: "offer", default: "Free First Wellness Exam + 20% Off First Groom" }, { name: "offerValue", default: "$95" }, { name: "petCount", default: "15,000+" }, { name: "rating", default: "4.9" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "landscaping": [{ name: "company", default: "Desert Bloom Landscaping" }, { name: "city", default: "Albuquerque" }, { name: "service", default: "landscape design & maintenance" }, { name: "offer", default: "Free Design Consultation + 3D Rendering" }, { name: "offerValue", default: "$450" }, { name: "projectCount", default: "1,200+" }, { name: "years", default: "15" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "cleaning": [{ name: "company", default: "Spotless Pro Cleaning" }, { name: "city", default: "Albuquerque" }, { name: "service", default: "home & office cleaning" }, { name: "offer", default: "$50 Off Your First Deep Clean" }, { name: "cleansDone", default: "22,000+" }, { name: "rating", default: "4.9" }, { name: "guarantee", default: "24-hour re-clean guarantee" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "childcare": [{ name: "center", default: "Little Explorers Learning Center" }, { name: "city", default: "Albuquerque" }, { name: "ages", default: "6 weeks \\u2013 5 years" }, { name: "offer", default: "Free Registration + First Week 50% Off" }, { name: "offerValue", default: "$275" }, { name: "familyCount", default: "900+" }, { name: "ratio", default: "1:4 infant ratio" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "tutoring": [{ name: "bizName", default: "Peak Performance Tutoring" }, { name: "city", default: "Albuquerque" }, { name: "subject", default: "math, reading & test prep" }, { name: "offer", default: "Free Skills Assessment + First Session Free" }, { name: "offerValue", default: "$190" }, { name: "studentCount", default: "3,400+" }, { name: "gradeGain", default: "1.5 letter grades" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "accounting": [{ name: "firm", default: "Summit CPA Advisors" }, { name: "cpa", default: "Daniel Ortiz, CPA" }, { name: "city", default: "Albuquerque" }, { name: "niche", default: "small business owners & contractors" }, { name: "offer", default: "Free Tax Savings Review" }, { name: "avgSavings", default: "$11,400" }, { name: "clientCount", default: "650+" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "photography": [{ name: "studio", default: "Golden Hour Studios" }, { name: "photographer", default: "Elena Vasquez" }, { name: "city", default: "Albuquerque" }, { name: "specialty", default: "family, branding & wedding photography" }, { name: "offer", default: "Mini Session + 5 Edited Images" }, { name: "offerPrice", default: "$149" }, { name: "offerValue", default: "$425" }, { name: "sessionCount", default: "2,100+" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "wedding-venue": [{ name: "venue", default: "The Cottonwood Estate" }, { name: "city", default: "Albuquerque" }, { name: "offer", default: "Complimentary Champagne Tour + Date-Hold" }, { name: "capacity", default: "250" }, { name: "weddingCount", default: "480+" }, { name: "startingPrice", default: "$4,900" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "moving": [{ name: "company", default: "Rock Steady Moving Co." }, { name: "city", default: "Albuquerque" }, { name: "service", default: "local & long-distance moving" }, { name: "offer", default: "Free In-Home Estimate + $100 Off Booking" }, { name: "movesDone", default: "9,800+" }, { name: "rating", default: "4.9" }, { name: "claimRate", default: "0.4%" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "webinar-live": [{ name: "headline", default: "The Client-Getting System Nobody Is Teaching (Live Training)" }, { name: "subhead", default: "A free live masterclass showing you the exact funnel + follow-up machine that t" }, { name: "host", default: "Jordan McKnight" }, { name: "hostCred", default: "Founder, McKnight Opportunity Group \u2014 builder of GrowthOS" }, { name: "date", default: "This Thursday" }, { name: "time", default: "7:00 PM Central" }, { name: "durationTxt", default: "60 minutes + live Q&A" }, { name: "seats", default: "200" }, { name: "bullet1", default: "The 5-stage pipeline that converts strangers into booked appointments on autopi" }, { name: "bullet2", default: "Why 90% of funnels leak money at the follow-up stage \u2014 and the 6-touch fix" }, { name: "bullet3", default: "The exact tech stack (all edge-native, all affordable) we deploy for every clie" }, { name: "cta", default: "Save My Free Seat" }, { name: "webinar", default: "(Zoom webinar/meeting ID to auto-register leads)" }, { name: "deadline", default: "(ISO date, countdown target)" }],
  "vsl": [{ name: "headline", default: "Watch: How We Add $30K+/Month To Service Businesses With One Automated System" }, { name: "subhead", default: "This short video breaks down the entire system \u2014 watch it before we take it dow" }, { name: "videoUrl", default: "(YouTube / Vimeo / Loom / Wistia / direct .mp4 URL)" }, { name: "cta", default: "Book My Free Strategy Call" }, { name: "ctaUrl", default: "#vsl-form" }, { name: "offer", default: "a free 30-minute strategy session where we map this exact system onto YOUR busi" }, { name: "proof1", default: "Tax firm: 214 qualified leads in 60 days" }, { name: "proof2", default: "Credit repair: $18K/mo recurring within one quarter" }, { name: "proof3", default: "Event brand: sold out 400 seats + 5-figure sponsors" }, { name: "host", default: "Jordan McKnight" }, { name: "gate", default: "(1 = lead-gate the CTA)" }, { name: "webinar", default: "(Zoom webinar/meeting ID to auto-register leads)" }, { name: "deadline", default: "(ISO date, countdown target)" }],
}

// Common params supported by EVERY funnel (funnelHead conversion/brand layer)
export const COMMON_PARAMS: ParamDef[] = [
  { name: 'seoTitle', default: '(page title tag)' },
  { name: 'seoDesc', default: '(meta description)' },
  { name: 'seoKeywords', default: '(meta keywords)' },
  { name: 'cta', default: '(sticky CTA button text)' },
  { name: 'exitTitle', default: '(exit-intent popup title)' },
  { name: 'exitDesc', default: '(exit-intent popup text)' },
  { name: 'theme', default: "('dark' for dark mode)" },
  { name: 'brandColor', default: '(hex like #d4a72c — remaps CTA/accent colors)' },
  { name: 'accentColor', default: '(hex — secondary gradient color)' },
  { name: 'bizLogo', default: '(https URL of client logo)' },
  { name: 'redirect', default: '(thank-you redirect URL)' },
  { name: 'ghlTag', default: '(comma-separated GHL tags for leads)' },
  { name: 'ga4', default: '(GA4 id G-XXXX)' },
  { name: 'gtm', default: '(GTM id)' },
  { name: 'metaPixel', default: '(Meta pixel id)' },
  { name: 'ttPixel', default: '(TikTok pixel id)' },
  { name: 'deadline', default: '(ISO date for countdown timers)' },
]

const ALLOWED: Record<string, Set<string>> = {}
export const allowedParams = (slug: string): Set<string> => {
  if (!ALLOWED[slug]) ALLOWED[slug] = new Set([...(FUNNEL_PARAMS[slug] || []), ...COMMON_PARAMS].map((p) => p.name))
  return ALLOWED[slug]
}
